# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLkTZg_lCXNe7LNvLmdwdOEgRF5qPOxa
"""

# pip install chatterbot --upgrade

# pip install chatterbot-corpus

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

import logging
# hide warning
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

# create chatbot instance
chatbot = ChatBot('Elliot')

# create list of statements in a conversation
conversation = [
    "hi what is the weather today?",
    "it's cold out",
    "okay I will bring a jacket"]

trainer = ListTrainer(chatbot)

trainer.train(conversation)

# get response!
response = chatbot.get_response("Do you think it's going to be warm outside today?")
print(response)
